version = 0.1
[default.deploy.parameters]
stack_name = "task-manager-pro-9000"
resolve_s3 = true
s3_prefix = "task-manager-pro-9000"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
image_repositories = []
