AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Resources:
  TasksTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: tasks
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      SSESpecification:
        SSEEnabled: true
      AttributeDefinitions:
        - AttributeName: taskId
          AttributeType: S
      KeySchema:
        - AttributeName: taskId
          KeyType: HASH
      # If we stored userId, I would probably have userId as the secondary/RANGE key
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
        # Because this is for a task management software
        # I think we are best off retaining change history

  TasksApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: TasksApi
      StageName: prod
      Cors: "'*'"

  GetTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/getTask.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 10
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        GetTask:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: GET
            RestApiId: !Ref TasksApi

  GetAllTasksFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/getAllTasks.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 10
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        GetAllTasks:
          Type: Api
          Properties:
            Path: /tasks
            Method: GET
            RestApiId: !Ref TasksApi

  CreateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/createTask.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 10
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        CreateTask:
          Type: Api
          Properties:
            Path: /tasks
            Method: POST
            RestApiId: !Ref TasksApi

  UpdateTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/updateTask.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 10
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        UpdateTask:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: PUT
            RestApiId: !Ref TasksApi

  DeleteTaskFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: dist/deleteTask.handler
      Runtime: nodejs18.x
      MemorySize: 128
      Timeout: 10
      CodeUri: .
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref TasksTable
      Events:
        DeleteTask:
          Type: Api
          Properties:
            Path: /tasks/{id}
            Method: DELETE
            RestApiId: !Ref TasksApi

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${TasksApi}.execute-api.${AWS::Region}.amazonaws.com/prod/"
