name: Deploy Backend

on:
  push:
    branches:
      - main
    paths:
      - "backend/src/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
